### ISSUE TITLE
github.GithubException.GithubException

### ISSUE THREAD

**Issue by tpmccallum** [IronCoreLabs/recrypt-rs#116]
Hi,
Getting one single error on [this PR](https://github.com/IronCoreLabs/recrypt-rs/pull/109).

The PR has been updated with the new backend features (then rebased with master etc.). No conflicts now, and all of the code related tests pass. 

Just not sure what the additional `.github/...` "Files changed" and `githubGithubException` error pertains to.
Any help would be greatly appreciated.

```
 Run harupy/comment-on-pr@c0522c42s
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"}
Run harupy/comment-on-pr@c0522c4
/usr/bin/docker run --name c27d3120b9ecbd68154e9a9b2dec1d8f765e55_b9eee0 --label c27d31 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_FILENAME -e INPUT_DOMAIN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/recrypt-rs/recrypt-rs":"/github/workspace" c27d31:20b9ecbd68154e9a9b2dec1d8f765e55
Traceback (most recent call last):
  File "/entrypoint.py", line 99, in <module>
    main()
  File "/entrypoint.py", line 95, in main
    pr.create_issue_comment(new_comment)
  File "/usr/local/lib/python3.7/site-packages/github/PullRequest.py", line 443, in create_issue_comment
    "POST", self.issue_url + "/comments", input=post_parameters
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"}
```

**Comment by clintfred** [comment]
I think this has been addressed by #117. We were experimenting with CI benchmarks being posted on PRs, but they have been disabled for now.
